In [1]:
pip install numpy

Requirement already satisfied: numpy in c:\users\rajpr\anaconda3\lib\site-packages (1.19.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\rajpr\anaconda3\lib\site-packages (1.1.3)
Requirement already satisfied: pytz>=2017.2 in c:\users\rajpr\anaconda3\lib\site-packages (from pandas) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\rajpr\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.15.4 in c:\users\rajpr\anaconda3\lib\site-packages (from pandas) (1.19.2)
Requirement already satisfied: six>=1.5 in c:\users\rajpr\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets
import pandas as pd  # Importing Pandas library
import os
import numpy as np
#import csv

In [4]:
ls

 Volume in drive C is OS
 Volume Serial Number is C4DF-4290

 Directory of C:\Users\rajpr

2022-04-09  02:21 PM    <DIR>          .
2022-04-09  02:21 PM    <DIR>          ..
2022-03-19  02:17 PM    <DIR>          .android
2022-04-08  11:43 PM            18,194 .bash_history
2021-03-06  07:13 PM    <DIR>          .cache
2022-04-09  02:37 PM    <DIR>          .conda
2022-04-09  02:12 PM                43 .condarc
2022-03-27  10:55 PM    <DIR>          .docker
2022-02-03  12:22 PM    <DIR>          .eclipse
2022-03-19  05:02 PM               208 .gitconfig
2022-03-10  11:49 AM    <DIR>          .gradle
2021-08-05  02:52 PM    <DIR>          .idlerc
2022-04-04  03:51 PM    <DIR>          .ipynb_checkpoints
2020-11-25  06:29 PM    <DIR>          .ipython
2020-11-25  06:32 PM    <DIR>          .jupyter
2022-03-25  07:12 PM                20 .lesshst
2022-03-28  01:37 PM    <DIR>          .m2
2022-03-21  05:11 PM    <DIR>          .matplotlib
2021-10-21  02:46 PM    <DIR>          .mchp_packs
2022-03-27  11:12 PM    <DIR>          .minikube
2021-09-10  11:59 AM    <DIR>          .mplabcomm
2022-03-17  08:45 AM    <DIR>          .p2
2022-03-28  02:47 PM    <DIR>          .redhat
2022-01-31  06:34 PM    <DIR>          .ssh
2021-07-22  06:26 PM    <DIR>          .stm32cubeide
2021-06-24  02:56 PM    <DIR>          .stm32cubemx
2021-06-24  02:55 PM    <DIR>          .stmcufinder
2021-01-12  10:52 AM    <DIR>          .tooling
2022-03-28  10:31 PM             1,824 .viminfo
2020-09-09  02:12 PM    <DIR>          .vscode
2020-05-20  10:01 AM           735,630 11_Dynamic-Allocation-2019.pdf
2021-10-28  03:40 PM    <DIR>          2021frontend
2020-09-05  10:29 PM    <DIR>          3D Objects
2020-11-25  05:46 PM    <DIR>          anaconda3
2021-12-17  04:56 PM    <DIR>          apifolder
2019-12-27  01:58 PM    <DIR>          Apple
2022-04-09  02:21 PM             6,552 BasicTreesCLASSIFICATION.ipynb
2021-08-17  02:22 PM               151 BullseyeCoverageError.txt
2021-11-02  06:09 PM               983 calcpi.cpp
2020-09-05  10:29 PM    <DIR>          Contacts
2022-04-03  07:33 PM    <DIR>          cpsc441local
2021-11-09  12:06 PM    <DIR>          detect-primes
2022-01-24  06:43 PM    <DIR>          Documents
2022-04-09  11:22 AM    <DIR>          Downloads
2022-04-02  03:16 PM    <DIR>          Dropbox
2022-04-08  10:58 AM    <DIR>          eclipse-workspace
2019-12-27  07:33 PM    <DIR>          Evernote
2021-12-15  08:48 PM    <DIR>          fatsim
2020-09-05  10:29 PM    <DIR>          Favorites
2022-04-04  08:40 PM             2,512 GaussianNaiveBayesCLASSIFICATION.ipynb
2022-02-07  06:30 PM    <DIR>          gitRepo
2022-03-19  02:44 PM    <DIR>          IdeaProjects
2021-01-12  12:58 PM                 0 javac
2020-09-05  10:29 PM    <DIR>          Links
2022-04-04  08:41 PM             2,378 logisticRegressionCLASSIFICATION.ipynb
2021-12-15  08:42 PM    <DIR>          memsim
2021-09-22  03:44 PM    <DIR>          MPLABXProjects
2022-04-04  01:53 PM            13,558 MultipleLinearREGRESSION .ipynb
2020-09-05  10:29 PM    <DIR>          Music
2022-03-25  06:46 PM    <DIR>          node_modules
2021-07-10  02:39 PM    <DIR>          OBC_software
2022-04-09  10:52 AM    <DIR>          OneDrive
2022-03-25  06:46 PM               339 package.json
2022-03-25  06:46 PM            52,919 package-lock.json
2021-10-01  11:54 PM    <DIR>          palindrome
2021-11-08  01:23 PM    <DIR>          pi-calc
2021-12-15  03:01 PM    <DIR>          Postman
2020-12-14  06:22 PM                 0 qms-bmh1.bmp
2020-12-14  06:22 PM                 0 qms-bmh2.bmp
2020-12-14  06:22 PM                 0 qms-bmh3.bmp
2020-12-14  06:22 PM                 0 quartus_web_rules_file.txt
2020-11-30  02:55 PM                 0 quartus2.ini
2020-12-14  06:58 PM            24,686 quartus2.qreg
2022-04-02  06:58 PM            11,237 randomforestREGRESSION.ipynb
2022-01-28  03:06 AM    <DIR>          reactproject
2022-04-02  06:56 PM            46,195 regressionKNN.ipynb
2019-06-11  01:23 AM    <DIR>          Roaming
2021-11-28  08:10 PM    <DIR>          safecall
2020-09-05  10:29 PM    <DIR>          Saved Games
2021-12-02  08:24 PM    <DIR>          scheduler
2022-03-29  11:28 AM    <DIR>          sellzer_ecommerce_microservice
2022-01-20  01:03 PM    <DIR>          seng438-a1-hudaabbas
2022-03-31  10:11 AM    <DIR>          seng438-a5-hudaabbas
2020-09-17  04:34 PM    <DIR>          source
2021-06-24  02:56 PM    <DIR>          STM32Cube
2021-06-24  02:54 PM    <DIR>          STM32CubeIDE
2022-03-21  11:35 PM            50,977 Untitled.ipynb
2022-03-28  06:37 PM               555 Untitled1.ipynb
2022-03-31  01:30 PM             7,664 Untitled2.ipynb
2020-09-05  10:29 PM    <DIR>          Videos
              26 File(s)        976,625 bytes
              64 Dir(s)  207,316,733,952 bytes free

In [5]:
import pandas as pd
data = pd.read_csv(r"C:\Users\rajpr\Downloads\archive\diabetes-dataset.csv")

data_np=data.to_numpy()
print('NUMPY data', data_np)

print(data_np.shape)

print(data_np[1:,1])

NUMPY data [[2.00e+00 1.38e+02 6.20e+01 ... 1.27e-01 4.70e+01 1.00e+00]
 [0.00e+00 8.40e+01 8.20e+01 ... 2.33e-01 2.30e+01 0.00e+00]
 [0.00e+00 1.45e+02 0.00e+00 ... 6.30e-01 3.10e+01 1.00e+00]
 ...
 [6.00e+00 8.50e+01 7.80e+01 ... 3.82e-01 4.20e+01 0.00e+00]
 [0.00e+00 1.29e+02 1.10e+02 ... 3.19e-01 2.60e+01 1.00e+00]
 [2.00e+00 8.10e+01 7.20e+01 ... 5.47e-01 2.50e+01 0.00e+00]]
(2000, 9)
[ 84. 145. 135. ...  85. 129.  81.]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               2000 non-null   int64
 1   Glucose                   2000 non-null   int64
 2   BloodPressure             2000 non-null   int64
 3   SkinThickness             2000 non-null   int64
 4   Insulin                   2000 non-null   int64
 5   BMI                       2000 non-null   float64
 6   DiabetesPedigreeFunction  2000 non-null   float64
 7   Age                       2000 non-null   int64
 8   Outcome                   2000 non-null   int64
dtypes: float64(2), int64(7)
memory usage: 140.8 KB

In [7]:
data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0
...,...,...,...,...,...,...,...,...,...
1995,2,75,64,24,55,29.7,0.370,33,0
1996,8,179,72,42,130,32.7,0.719,36,1
1997,6,85,78,0,0,31.2,0.382,42,0
1998,0,129,110,46,130,67.1,0.319,26,1
1999,2,81,72,15,76,30.1,0.547,25,0

In [8]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,2,138,62,35,0,33.6,0.127,47,1
1,0,84,82,31,125,38.2,0.233,23,0
2,0,145,0,0,0,44.2,0.630,31,1
3,0,135,68,42,250,42.3,0.365,24,1
4,1,139,62,41,480,40.7,0.536,21,0

In [9]:
data.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1995,2,75,64,24,55,29.7,0.370,33,0
1996,8,179,72,42,130,32.7,0.719,36,1
1997,6,85,78,0,0,31.2,0.382,42,0
1998,0,129,110,46,130,67.1,0.319,26,1
1999,2,81,72,15,76,30.1,0.547,25,0

In [10]:
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,3.703500,121.182500,69.145500,20.935000,80.254000,32.193000,0.470930,33.090500,0.342000
std,3.306063,32.068636,19.188315,16.103243,111.180534,8.149901,0.323553,11.786423,0.474498
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,63.500000,0.000000,0.000000,27.375000,0.244000,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,40.000000,32.300000,0.376000,29.000000,0.000000
75%,6.000000,141.000000,80.000000,32.000000,130.000000,36.800000,0.624000,40.000000,1.000000
max,17.000000,199.000000,122.000000,110.000000,744.000000,80.600000,2.420000,81.000000,1.000000

In [11]:
data.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.120405,0.149672,-0.063375,-0.076600,0.019475,-0.025453,0.539457,0.224437
Glucose,0.120405,1.000000,0.138044,0.062368,0.320371,0.226864,0.123243,0.254496,0.458421
BloodPressure,0.149672,0.138044,1.000000,0.198800,0.087384,0.281545,0.051331,0.238375,0.075958
SkinThickness,-0.063375,0.062368,0.198800,1.000000,0.448859,0.393760,0.178299,-0.111034,0.076040
Insulin,-0.076600,0.320371,0.087384,0.448859,1.000000,0.223012,0.192719,-0.085879,0.120924
BMI,0.019475,0.226864,0.281545,0.393760,0.223012,1.000000,0.125719,0.038987,0.276726
DiabetesPedigreeFunction,-0.025453,0.123243,0.051331,0.178299,0.192719,0.125719,1.000000,0.026569,0.155459
Age,0.539457,0.254496,0.238375,-0.111034,-0.085879,0.038987,0.026569,1.000000,0.236509
Outcome,0.224437,0.458421,0.075958,0.076040,0.120924,0.276726,0.155459,0.236509,1.000000

In [12]:
# blood pressure (predictor 1)
# patient age (predictor 2)
# skin thickness (predictor 3)
# insulin levels (predictor 4) 
# glucose level measurement (target outcome)
from sklearn.metrics import r2_score
import math
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
x = data.iloc[1:,[2,3,4,7]] #predictors
y = data.iloc[1:,1].values #outcome
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

# Fit regression model
n_neighbors = 2

knn = neighbors.KNeighborsRegressor(n_neighbors)
knn.fit(x_train, y_train)

knnTrain_predictY = knn.predict(x_train)
knnTest_predictY = knn.predict(x_test)

knn_trainR2 = r2_score(y_train, knnTrain_predictY)
knn_testR2 = r2_score(y_test, knnTest_predictY)

print("Performance of the k nearest neighbor model on training model (R^2) is: ", knn_trainR2)
print("Performance of the k nearest neighbor model on testing model (R^2) is:", knn_testR2)

knnTrain_RMSE = math.sqrt(mean_squared_error(y_train, knnTrain_predictY))
knnTest_RMSE = math.sqrt(mean_squared_error(y_test, knnTest_predictY))

print("Training Data RMSE (accuracy for regression): ", knnTrain_RMSE)
print("Testing Data RMSE (accuracy for regression): ", knnTest_RMSE)

print("knn predicted y for training: ", knnTrain_predictY)
print("knn predicted y for testing: ", knnTest_predictY)

#plt.subplot(2, 1, i + 1)
#plt.scatter(x_test[:,0], y_test[:,0], color="blue", label="data")
#plt.plot(y, y_train, color="navy", label="prediction")
#plt.axis("tight")
#plt.legend()
#plt.title("KNeighborsRegressor (k = %i, weights = '%s')" % (n_neighbors, weights))

#plt.tight_layout()
#plt.show()

Performance of the k nearest neighbor model on training model (R^2) is:  0.9080913741290846
Performance of the k nearest neighbor model on testing model (R^2) is: 0.5861035712109155
Training Data RMSE (accuracy for regression):  9.882950142041704
Testing Data RMSE (accuracy for regression):  19.89379947560942
knn predicted y for training:  [ 97. 105. 167. ... 166. 137. 165.]
knn predicted y for testing:  [108.5  90.  112.  131.5 122.  120.5  94.  128.   99.  180.5 131.  129.
 199.   92.5 148.5 182.  100.  109.5 148.5  91.  129.   91.  105.  129.
 170.  163.   72.  125.  111.   91.  108.   98.5 115.  120.5  97.  115.
 100.5 170.  178.  125.   88.  132.  128.  120.  134.5  94.5 112.   83.
 127.   84.  120.5 135.   72.  199.   83.   99.   99.   87.  112.  122.
 140.   88.5  91.   95.  111.  190.  116.  143.   89.   99.5 126.  125.
 141.  101.  103.5 144.  104.   95.5  81.  109.5 106.  184.   99.   98.
  91.  143.  135.  115.  126.   96.  173.  120.   91.5 126.  114.5 111.
 130.  125.  183.  138.5 135.  111.5 126.  105.  123.5  96.  105.    0.
  95.   92.5 117.  121.  172.  111.5 125.  102.  102.   83.5 158.5 118.
 124.5 126.5 155.5 123.  123.  102.  107.  189.5 142.5  97.5 126.  126.
 151.5 155.5 154.  132.  143.  120.5 107.  132.  109.  148.5 143.  126.
  96.   88.  162.5 101.  160.  145.5 136.  120.5 132.  146.  137.   91.5
  90.  172.  139.  115.  126.  146.  138.5 108.5 143.   95.5 141.   84.
 102.  112.   72.  167.   80.   79.  128.  158.5 145.5 134.5 119.5 106.5
 122.   88.5 104.  120.   92.5 107.5 120.  101.  138.   98.   56.  154.
 100.5 103.5 116.  168.  132.  173.  106.5  81.   87.  148.5 105.   95.
 187.   73.5 109.  163.   97.  108.  133.5 125.5  99.   97.  122.  132.
 119.5 132.5 105.   98.5 124.   85.  152.  144.  143.  101.  137.  122.5
  99.5 136.   97.  127.  170.   97.  116.  152.  100.5 134.   95.5 147.
  84.  134.5  92.5 173.   92.  125.  122.  127.  109.   44.   83.  168.
 102.  115.  102.  119.  148.5  96.   91.  108.5  92.  120.  143.  119.
 120.5 137.  131.  121.  129.  130.  135.  160.  154.  154.  131.   92.5
 101.   77.  127.5  95.  106.   94.  173.  158.   91.5  97.5 154.5 112.
 107.5  88.  194.  189.  137.   91.   44.  120.  109.5 103.  116.   91.5
  89.5 134.  119.  126.  119.   95.   88.5   0.   91.   92.   86.  162.5
 130.  109.   94.   89.  155.5 107.5  89.  145.5 158.  107.5 144.  157.
 173.   81.  120.5 137.  173.  107.5 144.  121.   97.  107.5  78.  101.
 168.   97.  143.  124.5 133.  109.5 176.   91.5 116.  109.5 155.  144.5
 118.   73.5 123.   79.  129.  119.5 141.  120.  107.  107.  120.  118.
 154.5 193.  142.5 136.  110.   90.  126.  123.  121.  148.5  73.5  92.5
 105.  120.5 195.  134.5  94.  120.  131.   84.  127.  141.  105.  142.
 184.  111.  123.  168.  155.   81.  123.  110.  147.  118.  130.5 106.5
 153.   94.  147.   81.   99.  126.5  88.  127.  128.  124.5 124.   80.
 113.  122.5 109.  154.  160.5 115.5  49.5 180.    0.  147.  106.  123.
 130.  133.5 130.  137.5 103.5 102.  127.5 183.    0.  181.  120.  189.5
 116.   84.  152.  138.5 151.5 193.  141.5 143.  132.   91.  127.  100.5
 112.  131.5 141.   97.  100.5  91.  135.  123.   94.5 123.5 126.   98.5
 156.  106.5 116.   87.  109.5 105.  189.   73.5 152.5 119.5 145.  154.
  90.5 124.5  95.  181.  189.  158.  114.   97.  123.  128.  116.  140.
 133.5 138.  106.   85.  138.5 104.   91.  109.  123.5 116.  104.  151.
 104.  103.  172.  158.  154.  156.   74.  116.  124.   94.  133.5 155.
  91.5 172.   94.  137.  115.5 123.  127.5 144.   83.   82.  127.   80.5
  83.   77.   89.   84.  115.  142.5 120.  115.  158.  180.5  91.5  93.
 169.  143.  195.  111.   95.   80.   95.  156.   74.   97.5 112.  127.
 173.   87.  100.5 119.5 173.  109.5   0.  117.  154.  168.   83.5  73.5
 115.  121.  175.  167.   83.  110.  195.  163.  102.  132.  112.  102.
 116.  138.  168.  140.5 122.  131.  156.  140.   85.  138.5 118.  176.
 194.  106.5  99.  173.  102.  132.5  91.5 115.  143.5 125.   80.  111.
 102.5 158.5 118.  128.  187.   90.  142.  134.  147.   99.   99.  108.5
  51.5 122.   95.   81.  110.  101.  172.  100.5  88.  109.   71.   90.5
 106.5  72.  143.  115.  114.  122.  179.  121.  144.  102.5 106.5  77.
  83.5 199.   77.  114.  104.5 147.5 180.5 150.5 141.  136.  120.  148.
 142.  181.  126.  110.  102.  108.   93.5 156.  130.5 163.   91.  115.
 129.  147.  158.5  78.  103.5  99.  102.  123.  115.   99.   89.  140.5]